import { Router } from "express";
import employees from "./employees.js";
import skills from "./skills.js";
import roles from "./roles.js";
import departments from "./departments.js";
import facilities from "./facilities.js";
import teams from "./teams.js";
import scenarios from "./scenarios.js";
import developmentPlans from "./development-plans.js";
import businessProcesses from "./business-processes.js";
import aiUseCases from "./ai-use-cases.js";
import reports from "./reports.js";
import notifications from "./notifications.js";
import successionRisks from "./succession-risks.js";
import analytics from "./analytics.js";
import admin from "./admin.js";

const router = Router();
router.use("/employees", employees);
router.use("/skills", skills);
router.use("/roles", roles);
router.use("/departments", departments);
router.use("/facilities", facilities);
router.use("/teams", teams);
router.use("/scenarios", scenarios);
router.use("/development-plans", developmentPlans);
router.use("/business-processes", businessProcesses);
router.use("/ai-use-cases", aiUseCases);
router.use("/reports", reports);
router.use("/notifications", notifications);
router.use("/succession-risks", successionRisks);
router.use("/analytics", analytics);
router.use("/admin", admin);
export default router;
