import test from "node:test";
import assert from "node:assert/strict";
import { randomUUID } from "node:crypto";

test("approved knowledge completes atomically and refreshes plans, history and readiness", { skip: !process.env.KNOWLEDGE_TEST_DATABASE_URL }, async () => {
  const url = new URL(process.env.KNOWLEDGE_TEST_DATABASE_URL);
  assert.equal(url.pathname, "/skillbridge_knowledge_test", "Use a dedicated skillbridge_knowledge_test database.");
  process.env.DATABASE_URL = url.toString();
  const { db, closeDatabase } = await import("../src/db/client.js");
  const { migrate } = await import("drizzle-orm/node-postgres/migrator");
  const { eq } = await import("drizzle-orm");
  const tables = await import("../src/db/schema.js");
  const service = await import("../src/services/knowledge.js");
  const { getSnapshot } = await import("../src/services/workforce.js");
  const { careerMetrics } = await import("../src/services/knowledge-schema.js");
  const suffix = randomUUID();
  const employeeId = `employee-${suffix}`, skillId = `skill-${suffix}`, moduleId = `module-${suffix}`, roleId = `role-${suffix}`, scenarioId = `scenario-${suffix}`;
  const { knowledgeActor } = await import("../src/middleware/knowledge-auth.js");
  const req = {};
  knowledgeActor(req, {}, () => {});
  const manager = req.actor;
  try {
    await migrate(db, { migrationsFolder: new URL("../src/db/migrations", import.meta.url).pathname });
    await db.insert(tables.skills).values({ id: skillId, name: `Test Handover ${suffix}`, category: "Operations" });
    await db.insert(tables.roles).values({ id: roleId, name: "Supervisor", jobFamily: "Operations", level: "Manager" });
    await db.insert(tables.employees).values({ id: employeeId, name: "Test Employee", title: "Operator" });
    await db.insert(tables.employeeSkills).values({ employeeId, skillId, proficiency: 1, yearsExperience: "1", verified: false });
    await db.insert(tables.roleSkillRequirements).values({ roleId, skillId, requiredLevel: 3, importance: 5 });
    await db.insert(tables.workforceScenarios).values({ id: scenarioId, name: "Test Readiness", targetDate: "2028-01-01", description: "Test" });
    await db.insert(tables.futureSkillRequirements).values({ scenarioId, skillId, requiredLevel: 3, requiredPeople: 1 });
    const content = { title: "Handover", summary: "Reviewed shift-handover procedure.", skills: [{ name: `Test Handover ${suffix}`, category: "Operations", requiredLevel: 3, audience: "Supervisors" }], tools: ["Log"], responsibilities: ["Supervisor"], procedures: ["Review log"], bestPractices: ["Confirm ownership"], risks: ["Missing handover"], checklist: ["Check log"], questions: ["Who owns follow-up?"], resources: ["Approved SOP"], audience: ["Supervisors"] };
    const mappings = [{ ...content.skills[0], skillId }];
    await db.insert(tables.knowledgeModules).values({ id: moduleId, kind: "MODULE", content, source: { kind: "document", name: "Test SOP", text: "Test source" }, mappings, generatedBy: manager.id });
    await assert.rejects(service.approveModule({ role: "employee" }, moduleId, 1), /manager/);
    const approved = await service.approveModule(manager, moduleId, 1);
    assert.equal(approved.status, "APPROVED");
    const [assigned] = await service.assignModule(manager, moduleId, { revision: approved.revision, employeeIds: [employeeId] });
    assert.equal(assigned.snapshot.revision, approved.revision);
    assert.deepEqual(await service.assignModule(manager, moduleId, { revision: approved.revision, employeeIds: [employeeId] }), []);
    await service.editModule(manager, moduleId, { revision: approved.revision, content: { ...content, summary: "An edited draft awaiting another review." }, mappings });
    const [snapshotAfterEdit] = await db.select().from(tables.knowledgeAssignments).where(eq(tables.knowledgeAssignments.id, assigned.id));
    assert.equal(snapshotAfterEdit.snapshot.content.summary, content.summary);
    await service.submitCompletion({ id: "learner", role: "employee", employeeId }, assigned.id, "Reviewed the log and correctly identified the escalation owner.");
    const [before] = await db.select().from(tables.employeeSkills).where(eq(tables.employeeSkills.employeeId, employeeId));
    assert.equal(before.proficiency, 1);
    const complete = await service.verifyCompletion(manager, assigned.id, [{ skillId, level: 3 }]);
    assert.equal(complete.status, "COMPLETED");
    await service.verifyCompletion(manager, assigned.id, [{ skillId, level: 3 }]);
    const snapshot = await getSnapshot({ scenarioId });
    assert.equal(snapshot.employeeSkills.find((s) => s.employeeId === employeeId).proficiency, 3);
    assert.equal(snapshot.plans.find((p) => p.id === assigned.planId).progress, 100);
    assert.equal(careerMetrics(snapshot, employeeId, { kind: "role", id: roleId }).readiness, 100);
    assert.equal(snapshot.gaps.find((g) => g.skillId === skillId).gap, 0);
    const context = await service.knowledgeContext(manager);
    assert.equal(context.sample, false);
    assert.equal(context.canManage, true);
    assert.ok(Array.isArray(context.courses));
    assert.ok(context.history.some((a) => a.id === assigned.id));
    const audit = await service.moduleAudit(manager, moduleId);
    assert.equal(audit.filter((e) => e.action === "COMPLETION_VERIFIED").length, 1);
  } finally {
    await db.delete(tables.knowledgeAudit).where(eq(tables.knowledgeAudit.moduleId, moduleId));
    await db.delete(tables.knowledgeAssignments).where(eq(tables.knowledgeAssignments.moduleId, moduleId));
    await db.delete(tables.knowledgeModules).where(eq(tables.knowledgeModules.id, moduleId));
    await db.delete(tables.employees).where(eq(tables.employees.id, employeeId));
    await db.delete(tables.roles).where(eq(tables.roles.id, roleId));
    await db.delete(tables.workforceScenarios).where(eq(tables.workforceScenarios.id, scenarioId));
    await db.delete(tables.skills).where(eq(tables.skills.id, skillId));
    await closeDatabase();
  }
});
